In [1]:
import csv

In [4]:
%precision 2 

'%.2f'

In [29]:
with open(r'C:\Users\Юрий\Desktop\Занятия\Coursera\mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
mpg[:3]    

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [7]:
len(mpg)

234

In [8]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [9]:
mpg[0].values()

dict_values(['1', 'audi', 'a4', '1.8', '1999', '4', 'auto(l5)', 'f', '18', '29', 'p', 'compact'])

In [11]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [12]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [21]:
CtyMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg / cyltypecount))
CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [22]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [ ]:
CylInClass=[]
for v in vehicleclass:
    cyltypecount = 0
    sumcyl = 0 
    for d in mpg:
        if d['class'] == v:
            sumcyl += float(d['cyl'])
            cyltypecount+=1
    CylInClass.append((v, sumcyl/cyltypecount))
CylInClass.sort(key=lambda x: x[0])
CylInClass

# Python Dates and Times

In [30]:
import datetime as dt
import time as tm

In [31]:
tm.time() #текущее время в миллисек. с даты 1.01.1970

1615798953.22

In [40]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2021, 3, 15, 16, 5, 55, 647885)

# Advanced Python Objects, map()

In [41]:
import numpy as np
import math

In [43]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [44]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b.shape

(2, 3)

In [49]:
d = np.zeros((2,3))
print(d)
e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [50]:
np.random.rand(2,3) #рандомно заполняем массив

array([[0.87186005, 0.6246649 , 0.08675859],
       [0.16640577, 0.94156255, 0.28313631]])

In [51]:
f = np.arange(10,50,2) #создаем одномерный массив из полсед-ти. 
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [52]:
np.linspace(0,2,15) #делим промежуток на 15 равных частей. 

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [54]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c= a - b 
print(c)
b = a * b 
print(b)

[ 9 18 27 36]
[ 10  40  90 160]


In [57]:
farenheit =np.array ([0,-10,-5,-15,0])
celcius = (farenheit - 32) * (5/9)
celcius

array([-17.77777778, -23.33333333, -20.55555556, -26.11111111,
       -17.77777778])

In [58]:
celcius > -20

array([ True, False, False, False,  True])

In [60]:
celcius%2 == 0

array([False, False, False, False, False])

In [61]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)

[[2 0]
 [0 4]]


In [62]:
print(A@B)

[[5 4]
 [3 4]]


In [65]:
array1 = np.array ([[1,2,3],[4,5,6]])
array2 = np.array ([[1.43,6.75,4.3],[4.2,1.0,3]])
array3 = array1 + array2
print(array3)

[[2.43 8.75 7.3 ]
 [8.2  6.   9.  ]]


In [66]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

41.68
9.0
2.4299999999999997
6.946666666666666


In [67]:
b = np.arange(1,16).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [90]:
from PIL import Image
import IPython as ip

In [89]:
im = Image.open(r'C:\Users\\Юрий\Desktop\chris.tiff')
array = np.array(im)
print(array.shape)

(200, 200)


In [91]:
ip.display(im)

TypeError: 'module' object is not callable

In [92]:
a = np.array([[1,2,],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
a[1,0]

3

In [95]:
np.array(a[[0,1,2],[0,1,1]])

array([1, 4, 6])

In [96]:
a[[0,1,2],[0,1,1]]

array([1, 4, 6])

In [97]:
a >5

array([[False, False],
       [False, False],
       [False,  True]])

In [103]:
b=a[2<a]

In [104]:
b

array([3, 4, 5, 6])

In [145]:
wines = np.genfromtxt(r'C:\Users\Юрий\Desktop\Занятия\Coursera\week1\dataset\winequality-red.csv', delimiter=';', skip_header=1)                  
print(wines)
print(np.shape(wines))

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
(1599, 12)


In [146]:
print(wines[:,0])

[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [147]:
print(wines[:,0:1])

[[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [148]:
print(wines[:,0:3])

[[7.4   0.7   0.   ]
 [7.8   0.88  0.   ]
 [7.8   0.76  0.04 ]
 ...
 [6.3   0.51  0.13 ]
 [5.9   0.645 0.12 ]
 [6.    0.31  0.47 ]]


In [149]:
print(wines[:,[0,2,10]])

[[ 7.4   0.    9.4 ]
 [ 7.8   0.    9.8 ]
 [ 7.8   0.04  9.8 ]
 ...
 [ 6.3   0.13 11.  ]
 [ 5.9   0.12 10.2 ]
 [ 6.    0.47 11.  ]]


In [150]:
print(wines[:,-1].mean())

5.6360225140712945


In [176]:
graduate_admission = np.genfromtxt(r'C:\Users\Юрий\Desktop\Занятия\Coursera\week1\dataset\Admission_Predict.csv', dtype=None,
                                   delimiter=',', skip_header=1, names=('Serial No.','GRE Score','TOEFL Score','University Rating','SOP','LOR' ,'CGPA','Research','Chance of Admit')) 

In [177]:
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [179]:
np.shape(graduate_admission)

(400,)

In [189]:
graduate_admission['CGPA'][0:10]

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 ])

In [182]:
graduate_admission['CGPA']=graduate_admission['CGPA']/10*4

In [183]:
graduate_admission['CGPA'][0:10]

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 ])

In [185]:
len(graduate_admission[(graduate_admission['Research'] == 1)])

219

In [187]:
graduate_admission[graduate_admission['Research'] == 1] [graduate_admission['Chance of Admit'].mean()]
graduate_admission[graduate_admission['Research'] == 0] [graduate_admission['Chance of Admit'].mean()]

ValueError: no field of name Chance of Admit

In [190]:
import re

In [192]:
text = 'This is a good day.'
if re.search('good', text):
    print('Wonderful!')
else: 
    print('Alas :(')

Wonderful!


In [193]:
text = 'Amy works diligently. Amy gets good grades. Our student Amy is succesful.'
re.split('Amy', text)

['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is succesful.']

In [194]:
re.findall('Amy', text)

['Amy', 'Amy', 'Amy']

In [197]:
text = 'Amy works diligently. Amy gets good grades. Our student Amy is succesful.'
re.search ('^Amy', text) # ^ - старт текста, $ - конец текста.

<re.Match object; span=(0, 3), match='Amy'>

In [198]:
# <re.Match object - всегда имеет значение True, т.к. что-то было найдено

In [241]:
grades='ACAAAABCBCBAA'
re.findall('BC', grades)

['BC', 'BC']

In [202]:
re.findall('[CB]', grades) #в re квадатные скобки это оператор позволяющий найти
                            # все вхождения необходимых знаков (C и B)

['C', 'B', 'C', 'B', 'C', 'B']

In [203]:
re.findall('[A][B-C]', grades) #ищем сочетания AC и AB

['AC', 'AB']

In [204]:
re.findall('AB|AC', grades) # ищем АВ or(|) АС

['AC', 'AB']

In [205]:
re.findall('[^A]', grades) #Ищем не А - '[^A]' внутри оператора SET - '^' это отрицание.  

['C', 'B', 'C', 'B', 'C', 'B']

In [208]:
re.findall('^[^A]', grades) #Ищем в начале строки not А

[]

In [209]:
#Оператор "Квантификатор". e{m,n}, где е - символ или сочетание которое мы ищем, m - мин. кол-во вхождений, n - макс. кол-во вхождений.  

In [217]:
re.findall('A{2,10}', grades) # шаблон ищет комбинацию от 2 до 10  А подряд. 

['AAAA', 'AA']

In [211]:
re.findall('A{1,1}A{1,1}', grades) #шаблон ищет комбинацию двух А стоящих рядом. т.е. в ААА будет АА,АА

['AA', 'AA', 'AA']

In [215]:
re.findall('A{2, 2}', grades) #между m и n не должно быть пробелов. иначе получим []

[]

In [238]:
re.findall('A{2}', grades) #если одно значение в фигурных скобках, то оно и m и n

['BC', 'BC']

In [242]:
re.findall('A{1,10}B{1,10}C{1,10}', grades)

['AAAABC']

In [229]:
with open (r'C:\Users\Юрий\Desktop\Занятия\Coursera\week1\dataset\ferpa.txt') as file:
    wiki=file.read()

In [230]:
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [1]:
import re
def names():
    simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""
    
    res = re.findall('[A-Z]\w+', simple_string)
    return res
    #raise NotImplementedError()

In [7]:
assert len(names()) == 4, "There are four names in the simple_string"
names()

['Amy', 'Mary', 'Ruth', 'Peter']